# Libraries and packages

# Tags options
options = [
    ('Action', 'Action'),
    ('Adventure', 'Adventure'),
    ('Singleplayer', 'Singleplayer'),
    ('Casual', 'Casual'),
    ('Strategy', 'Strategy'),
    ('Simulation', 'Simulation'),
    ('RPG', 'RPG'),
    ('Multiplayer', 'Multiplayer'),
    ('Great_Soundtrack', 'Great Soundtrack'),
    ('Atmospheric', 'Atmospheric'),
    ('2D', '2D'),
    ('Puzzle', 'Puzzle'),
    ('Early_Access', 'Early Access'),
    ('Open_World', 'Open World'),
    ('Story_Rich', 'Story Rich'),
    ('Co_op', 'Co-op'),
    ('Difficult', 'Difficult'),
    ('Shooter', 'Shooter'),
    ('Sci_fi', 'Sci-fi'),
    ('First_Person', 'First-Person'),
    ('Horror', 'Horror'),
    ('VR', 'VR'),
    ('Anime', 'Anime'),
    ('Pixel_Graphics', 'Pixel Graphics'),
    ('Funny', 'Funny'),
    ('Fantasy', 'Fantasy'),
    ('Platformer', 'Platformer'),
    ('Female_Protagonist', 'Female Protagonist'),
    ('Free_to_Play', 'Free to Play'),
    ('FPS', 'FPS'),
    ('Survival', 'Survival'),
    ('Gore', 'Gore'),
    ('Violent', 'Violent'),
    ('Sandbox', 'Sandbox'),
    ('Retro', 'Retro'),
    ('Arcade', 'Arcade'),
    ('Comedy', 'Comedy'),
    ('Classic', 'Classic'),
    ('Nudity', 'Third Person'),
    ('Third_Person', 'Nudity'),
    ('Massively_Multiplayer', 'Massively Multiplayer'),
    ('Exploration', 'Exploration'),
    ('Point_and_Click', 'Point & Click'),
    ('Visual_Novel', 'Visual Novel'),
    ('Turn_Based', 'Turn-Based'),
    ('Space', 'Space'),
    ('Sports', 'Sports'),
    ('Rogue_like', 'Rogue-like'),
    ('Tactical', 'Tactical'),
    ('Cute', 'Cute'),
    ('Racing', 'Racing'),
    ('Psychological_Horror', 'Psychological Horror'),
    ('Online_Co_Op', 'Online Co-Op'),
    ('Zombies', 'Zombies'),
    ('Family_Friendly', 'Family Friendly'),
    ('Sexual_Content', 'Sexual Content'),
    ('Local_Co_Op', 'Local Co-Op'),
    ('Local_Multiplayer', 'Local Multiplayer'),
    ('Controller', 'Controller'),
    ('Replay_Value', 'Replay Value'),
    ('Memes', 'Memes'),
    ('Building', 'Building'),
    ('RTS', 'RTS'),
    ('Turn_Based_Strategy', 'Turn-Based Strategy'),
    ('Side_Scroller', 'Side Scroller'),
    ('Fast_Paced', 'Fast-Paced'),
    ('Crafting', 'Crafting'),
    ('Action_RPG', 'Action RPG'),
    ('Mystery', 'Mystery'),
    ('Shoot_Em_Up', 'Dark'),
    ('Dark', "Shoot 'Em Up"),
    ('Management', 'Management'),
    ('Survival_Horror', 'Survival Horror'),
    ('Hack_and_Slash', 'Hack and Slash'),
    ('War', 'War'),
    ('Historical', 'Historical'),
    ('Physics', 'Physics'),
    ('Stealth', 'Stealth'),
    ('Rogue_lite', 'Rogue-lite'),
    ('PvP', 'PvP'),
    ('Realistic', 'Realistic'),
    ('Short', 'Short'),
    ('Isometric', 'Isometric'),
    ('RPGMaker', 'Moddable'),
    ('Moddable', 'RPGMaker'),
    ('Relaxing', 'Third-Person Shooter'),
    ('Third_Person_Shooter', 'Relaxing'),
    ('Bullet_Hell', 'Bullet Hell'),
    ('Top_Down', 'Top-Down'),
    ('Walking_Simulator', 'Walking Simulator'),
    ('Dungeon_Crawler', 'Dungeon Crawler'),
    ('JRPG', 'JRPG'),
    ('Fighting', 'Fighting'),
    ('Colorful', 'Colorful'),
]