# Libraries and packages

# Tags options
options = [
    ('Action', 'Action'),
    ('Adventure', 'Adventure'),
    ('Singleplayer', 'Singleplayer'),
    ('Casual', 'Casual'),
    ('Strategy', 'Strategy'),
    ('Simulation', 'Simulation'),
    ('RPG', 'RPG'),
    ('Multiplayer', 'Multiplayer'),
    ('Great Soundtrack', 'Great Soundtrack'),
    ('Atmospheric', 'Atmospheric'),
    ('2D', '2D'),
    ('Puzzle', 'Puzzle'),
    ('Early Access', 'Early Access'),
    ('Open World', 'Open World'),
    ('Story Rich', 'Story Rich'),
    ('Co-op', 'Co-op'),
    ('Difficult', 'Difficult'),
    ('Shooter', 'Shooter'),
    ('Sci-fi', 'Sci-fi'),
    ('First-Person', 'First-Person'),
    ('Horror', 'Horror'),
    ('VR', 'VR'),
    ('Anime', 'Anime'),
    ('Pixel Graphics', 'Pixel Graphics'),
    ('Funny', 'Funny'),
    ('Fantasy', 'Fantasy'),
    ('Platformer', 'Platformer'),
    ('Female Protagonist', 'Female Protagonist'),
    ('Free to Play', 'Free to Play'),
    ('FPS', 'FPS'),
    ('Survival', 'Survival'),
    ('Gore', 'Gore'),
    ('Violent', 'Violent'),
    ('Sandbox', 'Sandbox'),
    ('Retro', 'Retro'),
    ('Arcade', 'Arcade'),
    ('Comedy', 'Comedy'),
    ('Classic', 'Classic'),
    ('Third Person', 'Third Person'),
    ('Nudity', 'Nudity'),
    ('Massively Multiplayer', 'Massively Multiplayer'),
    ('Exploration', 'Exploration'),
    ('Point & Click', 'Point & Click'),
    ('Visual Novel', 'Visual Novel'),
    ('Turn-Based', 'Turn-Based'),
    ('Space', 'Space'),
    ('Sports', 'Sports'),
    ('Rogue-like', 'Rogue-like'),
    ('Tactical', 'Tactical'),
    ('Cute', 'Cute'),
    ('Racing', 'Racing'),
    ('Psychological Horror', 'Psychological Horror'),
    ('Online Co-Op', 'Online Co-Op'),
    ('Zombies', 'Zombies'),
    ('Family Friendly', 'Family Friendly'),
    ('Sexual Content', 'Sexual Content'),
    ('Local Co-Op', 'Local Co-Op'),
    ('Local Multiplayer', 'Local Multiplayer'),
    ('Controller', 'Controller'),
    ('Replay Value', 'Replay Value'),
    ('Memes', 'Memes'),
    ('Building', 'Building'),
    ('RTS', 'RTS'),
    ('Turn-Based Strategy', 'Turn-Based Strategy'),
    ('Side Scroller', 'Side Scroller'),
    ('Fast-Paced', 'Fast-Paced'),
    ('Crafting', 'Crafting'),
    ('Action RPG', 'Action RPG'),
    ('Mystery', 'Mystery'),
    ('Dark', 'Dark'),
    ("Shoot 'Em Up", "Shoot 'Em Up"),
    ('Management', 'Management'),
    ('Survival Horror', 'Survival Horror'),
    ('Hack and Slash', 'Hack and Slash'),
    ('War', 'War'),
    ('Historical', 'Historical'),
    ('Physics', 'Physics'),
    ('Stealth', 'Stealth'),
    ('Rogue-lite', 'Rogue-lite'),
    ('PvP', 'PvP'),
    ('Realistic', 'Realistic'),
    ('Short', 'Short'),
    ('Isometric', 'Isometric'),
    ('Moddable', 'Moddable'),
    ('RPGMaker', 'RPGMaker'),
    ('Third-Person Shooter', 'Third-Person Shooter'),
    ('Relaxing', 'Relaxing'),
    ('Bullet Hell', 'Bullet Hell'),
    ('Top-Down', 'Top-Down'),
    ('Walking Simulator', 'Walking Simulator'),
    ('Dungeon Crawler', 'Dungeon Crawler'),
    ('JRPG', 'JRPG'),
    ('Fighting', 'Fighting'),
    ('Colorful', 'Colorful')
]